//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp_Server6.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharp_Server6.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area23.At.Framework.Library.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualStudio 2022 C# 4.8.
        /// </summary>
        internal static string build_with {
            get {
                return ResourceManager.GetString("build_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fortune_u8 {
            get {
                object obj = ResourceManager.GetObject("fortune.u8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/heinrichelsigan/area23.at/.
        /// </summary>
        internal static string github_uri {
            get {
                return ResourceManager.GetString("github_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Area23.At.Framework.Library&lt;/h1&gt;
        ///&lt;p&gt;C# .Net Samples for apache2 mod_mono
        ///by Heinrich Elsigan (&lt;a href=&quot;mailto:he@area23.at&quot;&gt;heinrich.elsigan@area23.at&lt;/a&gt;).
        ///&lt;/p&gt;
        ///&lt;hr /&gt;
        ///Code is open source under GPL 3 and publicly accessible via &lt;a href=&quot;https://github.com/&quot; target=&quot;_blank&quot;&gt;GitHub&lt;/a&gt; repository &lt;a href=&quot;https://github.com/heinrichelsigan/area23.at/&quot; target=&quot;_blank&quot;&gt;github.com/heinrichelsigan/area23.at&lt;/a&gt;.
        ///&lt;br /&gt;.
        /// </summary>
        internal static string help_text {
            get {
                return ResourceManager.GetString("help_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { 
        /// 	&quot;quiz&quot;: { 
        /// 		&quot;sport&quot;: { 
        /// 			&quot;q1&quot;: { 
        /// 				&quot;question&quot;: &quot;Which one is correct team name in NBA?&quot;, 
        /// 					&quot;options&quot;: [ 
        /// 						&quot;New York Bulls&quot;, 
        /// 							&quot;Los Angeles Kings&quot;, 
        /// 							&quot;Golden State Warriros&quot;, 
        /// 							&quot;Huston Rocket&quot; 
        /// 						], 
        /// 					&quot;answer&quot;: &quot;Huston Rocket&quot; 
        /// 				} 
        /// 			}, 
        /// 		&quot;maths&quot;: { 
        /// 			&quot;q1&quot;: { 
        /// 				&quot;question&quot;: &quot;5 + 7 = ?&quot;, 
        /// 					&quot;options&quot;: [ 
        /// 						&quot;10&quot;, 
        /// 						&quot;11&quot;, 
        /// 						&quot;12&quot;, 
        /// 						&quot;13&quot; 
        /// 					], 
        /// 					&quot;answer&quot;: &quot;12&quot; 
        ///				}, 
        /// 			&quot;q2&quot;: { 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json_sample0 {
            get {
                return ResourceManager.GetString("json_sample0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string json_sample1 {
            get {
                return ResourceManager.GetString("json_sample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fcKZpNSKLTs=.
        /// </summary>
        internal static string M0Rlc0l2 {
            get {
                return ResourceManager.GetString("M0Rlc0l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEJBQjUxMEJBQjUxMEJBQjUxMEJBQjUxMEJBQjUwQkE=.
        /// </summary>
        internal static string Q0FTVExF {
            get {
                return ResourceManager.GetString("Q0FTVExF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GvJd0SRyg3AcTF4Sidyrn/nJM1BNUJqKms19FZKx1Z4=.
        /// </summary>
        internal static string Qk9VTkNF {
            get {
                return ResourceManager.GetString("Qk9VTkNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0ersgfaO/uP7+HrpTwZjU9VoyobLofw7KvwCAcOVMRc=.
        /// </summary>
        internal static string QWVzS2V5 {
            get {
                return ResourceManager.GetString("QWVzS2V5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6pU0BotI3zzF0cWKz56bkQ==.
        /// </summary>
        internal static string QWVzSXY0 {
            get {
                return ResourceManager.GetString("QWVzSXY0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C6S5DegwbQopnitJnAu/g4BXa0M32ZGZ.
        /// </summary>
        internal static string RGVzS2V5 {
            get {
                return ResourceManager.GetString("RGVzS2V5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v2.24.831.
        /// </summary>
        internal static string version_name {
            get {
                return ResourceManager.GetString("version_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/heinrichelsigan/area23.at/.
        /// </summary>
        internal static string wiki_uri {
            get {
                return ResourceManager.GetString("wiki_uri", resourceCulture);
            }
        }
    }
}
